services:
  trackme:
    build:
      context: trackme
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./trackme:/app
      - exclude:/app/node_modules
    restart: 'unless-stopped'

  postgres:
    ports:
      - 5432:5432

volumes:
  exclude:
