services:
  smtp-proxy:
    build:
      context: smtp-proxy
    ports:
      - "25:25"
    volumes:
      - ./smtp-proxy:/app
    restart: 'unless-stopped'

  trackme:
    build:
      context: trackme
    ports:
      - "3000:3000"
    volumes:
      - ./trackme/data:/data
    environment:
      - SQLITE_DB_PATH=/data/sqlite.db
    restart: 'unless-stopped'