services:
  smtp-proxy:
    build: smtp-proxy/
    ports:
      - "25:25"
    volumes:
      - ./smtp-proxy:/app
    restart: 'unless-stopped'

  trackme:
    build: trackme/
    ports:
      - "3000:3000"
    volumes:
      - ./trackme:/app
      - sqlite-data:/sqlite
    environment:
      - SQLITE_DB_PATH=/sqlite/data.db
    restart: 'unless-stopped'

volumes:
  sqlite-data: